version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: agentix_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3388:3308" # Puerto externo para gestión (ej. DBeaver)
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - agentix_default

  api:
    image: ghcr.io/inntek15dev-lang/agentix-api:latest
    container_name: agentix_api
    restart: always
    environment:
      - NODE_ENV=preproduction
      - DB_HOST=db
      - DB_USER=root
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PIZZA_API_URL=${PIZZA_API_URL}
      - PIZZA_API_KEY=${PIZZA_API_KEY}
      - PORT=4077
    # Forzamos la lectura del .env que está en la raíz del servidor
    env_file:
      - .env
    ports:
      - "4088:4088"
    depends_on:
      - db
    networks:
      - abastible_default

  frontend:
    image: ghcr.io/inntek15dev-lang/agentix-front:latest
    container_name: agentix_front
    restart: always
    environment:
      - VITE_API_URL=http://23.81.206.147:4088/api
    ports:
      - "8088:88"
    depends_on:
      - api
    networks:
      - abastible_default

networks:
  abastible_default:
    driver: bridge
