# Etapa 1: Build de React con Vite
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Vite construirá de forma agnóstica sin VITE_API_URL
RUN npm run build

# Etapa 2: Servidor Nginx
FROM nginx:alpine
# Copiamos la build de Vite
COPY --from=build /app/dist /usr/share/nginx/html

# Ajustes Nginx para SPA (React Router / Vite)
RUN sed -i '10i \\n    location / {\n        try_files $uri /index.html;\n    }\n' /etc/nginx/conf.d/default.conf

# Script de entrada para inyectar variables de entorno en runtime
COPY env.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/env.sh

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
